language: java
script: ant -Dprotobuf.uptodate=true test checkstyle
notifications:
  email:
    recipients:
      - hridesh@iastate.edu
      - rdyer@bgsu.edu
    on_success: change
    on_failure: always
